CREATE TABLE TBRLEATORIO
(
	IDRELATORIO INT IDENTITY (1,1),
	IDESPECIME INT NOT NULL,																	-- ID ESPÉCIME
	IDESPECIE INT NOT NULL,																			-- ESPÉCIE
	COORD VARCHAR(50),																				-- COORDENADAS
	IMAGEM VARCHAR(256),																			-- ENDEREÇO DA IMAGEM
	DESCRICAOIMG VARCHAR(256),																		-- DESCRIÇÃO IMAGEM (AUDIODESCRIÇÃO)
	ESTADO CHAR(1),																					-- STATUS (DEFINIR)
	DAP DECIMAL(4,2),																				-- DIÂMETRO NA ALTURA DO PEITO
	DATPLANT SMALLDATETIME,																			-- DATA DE PLANTIU
	DATACAD SMALLDATETIME,																			-- DATA DE CADASTRO					
	IDCADADM INT																					-- ID DO USUÁRIO
);

-- Add Column with Default Current Date Time
ALTER TABLE TBRELATORIO
ADD Date DATETIME NOT NULL DEFAULT (GETDATE());


CREATE SEQUENCE idrelatorio_seq
  START WITH 1
  INCREMENT BY 1
  NO CYCLE;

-- Step 1: Turn ON IDENTITY_INSERT
SET IDENTITY_INSERT TBRELATORIO ON;

-- Step 2: Perform the INSERT operation
INSERT INTO TBRELATORIO (IDRELATORIO, IDESPECIME, IDESPECIE, COORD, IMAGEM, DESCRICAOIMG, ESTADO, DAP, DATPLANT, DATACAD, IDCADADM)
  SELECT NEXT VALUE FOR idrelatorio_seq, IDESPECIME, IDESPECIE, COORD, IMAGEM, DESCRICAOIMG, ESTADO, DAP, DATPLANT, DATACAD, IDCADADM
  FROM TBESPECIME
  WHERE Date >= CAST(DATEADD(day, -30, GETDATE()) as DATE);

-- Step 3: Turn OFF IDENTITY_INSERT
SET IDENTITY_INSERT TBRELATORIO OFF;