```mermaid
sequenceDiagram
  actor U as admin:Usuário
  participant UI as main:MainPage
  participant D as sdb:SignaDatabase
  participant S as modulovalidação:ValidadordeSenha

$ git config --global user.name "Drynee"
  
  activate U

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
 
  %% Criar Admin
  U ->> UI: createAdmin
    activate UI
  U ->> UI: inputNome,CPF,Matrícula,Email
  U ->> UI: inputSenha,ConfirmaSenha

  UI ->> S: validateSenha
    activate S
    deactivate S
    deactivate UI
  U ->> UI: saveAdmin
    activate UI

  UI ->> D: addAdmin
    deactivate UI
    activate D
    deactivate D

  deactivate U

```
