sequenceDiagram
  actor U as admin:Usuário
  participant UI as main:MainPage
  participant D as sdb:SignaDatabase
  participant S as modulovalidação:ValidadordeSenha

  
  activate U

 
  %% Exclude Admin
  U ->> UI: selecttAdmin
  U ->> UI: clickExcludeAdmin
  UI -->> U: "Insira Senha"
  U ->> UI: inputSenha
  UI ->> S: validateSenha

  U ->> UI: confirmExclusion

  UI ->> D: requestDeactivation
  D ->> D: deactivateAdmin

  deactivate U